[package]
name = "witchcraft-logging-api"
version = "2.0.0"
edition = "2024"
license = "Apache-2.0"
description = "Witchcraft log API types"
repository = "https://github.com/palantir/witchcraft-rust-logging"

[build-dependencies]
conjure-codegen = "5.0.0"

[dependencies]
conjure-object = "5.0.0"
