[package]
name = "witchcraft-wasm-logger"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "A Witchcraft logger that sends logs to the browser console"
repository = "https://github.com/palantir/witchcraft-rust-logging"
categories = ["wasm"]

[dependencies]
conjure-serde = "5.0.0"
web-sys = {  version = "0.3.81", features = ["console"] }
witchcraft-log = { version = "5.0.0", path = "../witchcraft-log" }
witchcraft-log-util = { version = "2.0.0", path = "../witchcraft-log-util" }

